# Generated by Django 5.1.15 on 2026-06-21 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('target_year', models.PositiveIntegerField(verbose_name='Buchungsjahr')),
                ('wishlist_open', models.DateField(verbose_name='Anmeldung ab')),
                ('wishlist_close', models.DateField(verbose_name='Anmeldung bis')),
                ('status', models.CharField(choices=[('open', 'Anmeldung offen'), ('drawn', 'Ausgelost'), ('closed', 'Abgeschlossen')], default='open', max_length=10, verbose_name='Status')),
                ('seed', models.BigIntegerField(blank=True, null=True, verbose_name='Zufalls-Seed')),
            ],
            options={
                'verbose_name': 'Buchungsperiode',
                'verbose_name_plural': 'Buchungsperioden',
                'ordering': ['-target_year'],
            },
        ),
        migrations.CreateModel(
            name='EquivalenceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Äquivalenzklasse',
                'verbose_name_plural': 'Äquivalenzklassen',
            },
        ),
        migrations.CreateModel(
            name='LotteryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Durchgeführt')),
                ('seed', models.BigIntegerField(verbose_name='Seed')),
                ('log_text', models.TextField(blank=True, verbose_name='Protokoll')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Zusammenfassung')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='booking.bookingperiod', verbose_name='Periode')),
            ],
            options={
                'verbose_name': 'Losdurchlauf',
                'verbose_name_plural': 'Losdurchläufe',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, verbose_name='Anzeigename')),
                ('factor', models.FloatField(default=1.0, verbose_name='Ausgleichsfaktor')),
                ('annual_night_budget', models.PositiveIntegerField(default=50, verbose_name='Nächte/Jahr')),
                ('wish_night_budget', models.PositiveIntegerField(default=25, verbose_name='Nächte über Wunschliste')),
                ('is_external', models.BooleanField(default=False, verbose_name='Externer Gast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Login-Konto')),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('size_sqm', models.PositiveIntegerField(default=0, verbose_name='Größe (m²)')),
                ('min_occupancy', models.PositiveIntegerField(default=1, verbose_name='Min. Personen')),
                ('max_occupancy', models.PositiveIntegerField(default=2, verbose_name='Max. Personen')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('eq_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarters', to='booking.equivalenceclass', verbose_name='Äquivalenzklasse')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiere',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Anreise')),
                ('end', models.DateField(verbose_name='Abreise (exkl.)')),
                ('source', models.CharField(choices=[('lottery', 'Losung'), ('spontaneous', 'Spontanbuchung'), ('external', 'Externe Buchung')], max_length=12, verbose_name='Quelle')),
                ('via_substitution', models.BooleanField(default=False, verbose_name='Ausweichquartier')),
                ('contested', models.BooleanField(default=False, verbose_name='Umkämpft')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='booking.bookingperiod', verbose_name='Periode')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='booking.member', verbose_name='Mitglied')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='booking.quarter', verbose_name='Quartier')),
            ],
            options={
                'verbose_name': 'Zuteilung',
                'verbose_name_plural': 'Zuteilungen',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priorität (1 = höchste)')),
                ('start', models.DateField(verbose_name='Anreise')),
                ('end', models.DateField(verbose_name='Abreise (exkl.)')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='booking.member', verbose_name='Mitglied')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='booking.bookingperiod', verbose_name='Periode')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='booking.quarter', verbose_name='Wunschquartier')),
            ],
            options={
                'verbose_name': 'Wunsch',
                'verbose_name_plural': 'Wünsche',
                'ordering': ['member', 'priority'],
            },
        ),
    ]
