# Generated by Django 5.1.15 on 2026-06-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('start', models.DateField(verbose_name='Buchbar ab')),
                ('end', models.DateField(verbose_name='Buchbar bis (exkl.)')),
                ('applies_to_all', models.BooleanField(default=True, verbose_name='Gilt für alle Quartiere')),
                ('active', models.BooleanField(default=True, verbose_name='Freigeschaltet')),
                ('quarters', models.ManyToManyField(blank=True, related_name='booking_windows', to='booking.quarter', verbose_name='Nur diese Quartiere (wenn nicht global)')),
            ],
            options={
                'verbose_name': 'Buchungszeitraum',
                'verbose_name_plural': 'Buchungszeiträume',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='NightTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('nights', models.PositiveIntegerField(verbose_name='Tage')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='booking.member', verbose_name='Von Mitglied')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='booking.member', verbose_name='An Mitglied')),
            ],
            options={
                'verbose_name': 'Tage-Übertragung',
                'verbose_name_plural': 'Tage-Übertragungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
