# Generated by Django 5.1.15 on 2026-06-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingwindow_nighttransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_min_nights', models.PositiveIntegerField(default=3, help_text='Gilt, wenn keine Saison-Regel etwas Strengeres vorgibt.', verbose_name='Mindestnächte (Standard)')),
            ],
            options={
                'verbose_name': 'Buchungsregel (global)',
                'verbose_name_plural': 'Buchungsregeln (global)',
            },
        ),
        migrations.CreateModel(
            name='SeasonRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Bezeichnung')),
                ('start', models.DateField(verbose_name='Von')),
                ('end', models.DateField(verbose_name='Bis (exkl.)')),
                ('min_nights', models.PositiveIntegerField(blank=True, help_text='z.B. 7 für Juli/August. Leer = Standard.', null=True, verbose_name='Mindestnächte')),
                ('max_parallel_units', models.PositiveIntegerField(blank=True, help_text='z.B. 2 in Schulferien/an Feiertagen. Leer = unbegrenzt.', null=True, verbose_name='Max. gleichzeitige Wohneinheiten')),
                ('max_stay_nights', models.PositiveIntegerField(blank=True, help_text='Einheiten-Nächte innerhalb des Zeitraums, z.B. 14 für die BB-Sommerferien. Leer = kein Deckel.', null=True, verbose_name='Max. Nächte je Partei (Deckel)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Saison-Regel',
                'verbose_name_plural': 'Saison-Regeln',
                'ordering': ['start'],
            },
        ),
    ]
