# Generated by Django 5.1.15 on 2026-06-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingpolicy_seasonrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Bezeichnung')),
                ('start', models.DateField(verbose_name='Von')),
                ('end', models.DateField(verbose_name='Bis (exkl.)')),
                ('region', models.CharField(default='Berlin', max_length=40, verbose_name='Region')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Schulferien',
                'verbose_name_plural': 'Schulferien',
                'ordering': ['start'],
            },
        ),
        migrations.AddField(
            model_name='wish',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='Im Lostopf'),
        ),
        migrations.AddField(
            model_name='wish',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am'),
        ),
    ]
