# Generated by Django 5.1.15 on 2026-06-22 09:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    """Führt die alten Daten in das zusammengeführte Modell über:

    * Status der Perioden neu abbilden (open→wishes_open, drawn→lottery_done,
      closed→ended) und den Zeitraum [start, end) aufs Buchungsjahr setzen.
    * Bestehende Buchungszeiträume (BookingWindow) in Perioden mit dem Status
      „Freie Bebuchbarkeit“ (bzw. „Unterbrochen“, wenn gesperrt) überführen.
    * Genau ein Regelwerk (BookingPolicy) sicherstellen und alle bestehenden
      Saison-Regeln und Schulferien diesem zuordnen.
    """
    BookingPeriod = apps.get_model("booking", "BookingPeriod")
    BookingWindow = apps.get_model("booking", "BookingWindow")
    BookingPolicy = apps.get_model("booking", "BookingPolicy")
    SeasonRule = apps.get_model("booking", "SeasonRule")
    SchoolHoliday = apps.get_model("booking", "SchoolHoliday")

    placeholder = datetime.date(2000, 1, 1)
    status_map = {"open": "wishes_open", "drawn": "lottery_done", "closed": "ended"}
    for p in BookingPeriod.objects.all():
        changed = False
        new_status = status_map.get(p.status)
        if new_status:
            p.status = new_status
            changed = True
        if p.start == placeholder and p.target_year:
            p.start = datetime.date(p.target_year, 1, 1)
            changed = True
        if p.end == placeholder and p.target_year:
            p.end = datetime.date(p.target_year + 1, 1, 1)
            changed = True
        if changed:
            p.save()

    for w in BookingWindow.objects.all():
        period = BookingPeriod.objects.create(
            name=w.name,
            target_year=w.start.year,
            start=w.start,
            end=w.end,
            status="free_booking" if w.active else "suspended",
            applies_to_all=w.applies_to_all,
        )
        period.quarters.set(list(w.quarters.all()))

    policy = BookingPolicy.objects.first()
    if policy is None:
        policy = BookingPolicy.objects.create()
    SeasonRule.objects.filter(policy__isnull=True).update(policy=policy)
    SchoolHoliday.objects.filter(policy__isnull=True).update(policy=policy)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_schoolholiday_wish_submitted_wish_submitted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingperiod",
            options={
                "ordering": ["-target_year"],
                "verbose_name": "Buchungsperiode (Zeitraum)",
                "verbose_name_plural": "Buchungsperioden (Zeiträume)",
            },
        ),
        migrations.AlterModelOptions(
            name="bookingpolicy",
            options={
                "verbose_name": "Buchungsregeln",
                "verbose_name_plural": "Buchungsregeln",
            },
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="applies_to_all",
            field=models.BooleanField(
                default=True, verbose_name="Gilt für alle Quartiere"
            ),
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="end",
            field=models.DateField(
                default=datetime.date(2000, 1, 1),
                verbose_name="Zeitraum buchbar bis (exkl.)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="quarters",
            field=models.ManyToManyField(
                blank=True,
                related_name="booking_periods",
                to="booking.quarter",
                verbose_name="Nur diese Quartiere (wenn nicht global)",
            ),
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="start",
            field=models.DateField(
                default=datetime.date(2000, 1, 1), verbose_name="Zeitraum buchbar ab"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_holidays",
                to="booking.bookingpolicy",
                verbose_name="Regelwerk",
            ),
        ),
        migrations.AddField(
            model_name="seasonrule",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_rules",
                to="booking.bookingpolicy",
                verbose_name="Regelwerk",
            ),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("wishes_open", "Für Wunsch-Einträge freigegeben"),
                    ("lottery_ready", "Zur Auslosung freigegeben"),
                    ("lottery_done", "Auslosung beendet"),
                    ("free_booking", "Freie Bebuchbarkeit innerhalb Zeitraum"),
                    ("ended", "Beendet"),
                    ("suspended", "Unterbrochen"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="wishlist_close",
            field=models.DateField(blank=True, null=True, verbose_name="Anmeldung bis"),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="wishlist_open",
            field=models.DateField(blank=True, null=True, verbose_name="Anmeldung ab"),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="BookingWindow",
        ),
    ]
