# Generated by Django 5.1.15 on 2026-06-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_bookingperiod_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingAllocation",
            fields=[],
            options={
                "verbose_name": "Anstehende Buchung",
                "verbose_name_plural": "Anstehende Buchungen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("booking.allocation",),
        ),
    ]
