# Generated by Django 5.1.15 on 2026-06-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_upcomingallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="persons",
            field=models.PositiveIntegerField(default=1, verbose_name="Personen"),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Nachricht")),
                (
                    "url",
                    models.CharField(blank=True, max_length=200, verbose_name="Link"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Gelesen")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benachrichtigung",
                "verbose_name_plural": "Benachrichtigungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(verbose_name="Anreise")),
                ("end", models.DateField(verbose_name="Abreise (exkl.)")),
                (
                    "persons",
                    models.PositiveIntegerField(default=1, verbose_name="Personen"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "fulfilled",
                    models.BooleanField(
                        default=False, verbose_name="Frei geworden / erledigt"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Benachrichtigt am"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="booking.quarter",
                        verbose_name="Quartier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wartelisten-Eintrag",
                "verbose_name_plural": "Warteliste (Spontanbuchung)",
                "ordering": ["start"],
            },
        ),
    ]
