# Generated by Django 5.1.15 on 2026-06-22 10:49 (Operationen umsortiert +
# Daten-Migration: alte Datumsfelder -> Monat/Tag, bevor sie entfernt werden).

from django.db import migrations, models


def forwards(apps, schema_editor):
    """Übernimmt die bisherigen Start-/End-Daten in die neuen Monat/Tag-Felder
    (die Regeln gelten künftig jährlich, ohne Jahr)."""
    for name in ("SeasonRule", "SchoolHoliday"):
        Model = apps.get_model("booking", name)
        for obj in Model.objects.all():
            obj.start_month, obj.start_day = obj.start.month, obj.start.day
            obj.end_month, obj.end_day = obj.end.month, obj.end.day
            obj.save(update_fields=[
                "start_month", "start_day", "end_month", "end_day",
            ])


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_allocation_persons_notification_waitlistentry"),
    ]

    operations = [
        # 1) Neue Felder hinzufügen
        migrations.AddField(
            model_name="quarter",
            name="accessible",
            field=models.BooleanField(
                default=False,
                help_text="Quartier ist barrierearm bzw. barrierefrei erreichbar.",
                verbose_name="Barrierearm/-frei",
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="season_end_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Buchbar bis einschl. (Tag)"
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="season_end_month",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Buchbar bis einschl. (Monat)"
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="season_start_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Buchbar ab (Tag)"
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="season_start_month",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Buchbar ab (Monat)"
            ),
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="end_day",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Bis exkl. (Tag)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Bis exkl. (Monat)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="max_parallel_units",
            field=models.PositiveIntegerField(
                blank=True, help_text="Leer = unbegrenzt.", null=True,
                verbose_name="Max. gleichzeitige Wohneinheiten",
            ),
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="max_stay_nights",
            field=models.PositiveIntegerField(
                blank=True, help_text="Leer = kein Deckel.", null=True,
                verbose_name="Max. Nächte je Partei (Deckel)",
            ),
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="min_nights",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leer = keine Mindestnächte-Regel in diesem Zeitraum.",
                null=True, verbose_name="Mindestnächte",
            ),
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="start_day",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Von (Tag)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolholiday",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Von (Monat)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonrule",
            name="end_day",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Bis exkl. (Tag)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonrule",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Bis exkl. (Monat)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonrule",
            name="start_day",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Von (Tag)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonrule",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Von (Monat)"
            ),
            preserve_default=False,
        ),
        # 2) Bestehende Daten übernehmen
        migrations.RunPython(forwards, migrations.RunPython.noop),
        # 3) Alte Datumsfelder entfernen
        migrations.RemoveField(model_name="schoolholiday", name="end"),
        migrations.RemoveField(model_name="schoolholiday", name="start"),
        migrations.RemoveField(model_name="seasonrule", name="end"),
        migrations.RemoveField(model_name="seasonrule", name="start"),
        # 4) Meta-Optionen anpassen
        migrations.AlterModelOptions(
            name="schoolholiday",
            options={
                "ordering": ["start_month", "start_day"],
                "verbose_name": "Schulferien",
                "verbose_name_plural": "Schulferien",
            },
        ),
        migrations.AlterModelOptions(
            name="seasonrule",
            options={
                "ordering": ["start_month", "start_day"],
                "verbose_name": "Saison-Regel",
                "verbose_name_plural": "Saison-Regeln",
            },
        ),
    ]
