# Generated by Django 5.1.15 on 2026-06-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0008_alter_schoolholiday_options_alter_seasonrule_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Nachricht")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("accepted", "Angenommen"),
                            ("declined", "Abgelehnt"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Beantwortet am"
                    ),
                ),
                (
                    "from_allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_from",
                        to="booking.allocation",
                        verbose_name="Eigene Buchung",
                    ),
                ),
                (
                    "from_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_sent",
                        to="booking.member",
                        verbose_name="Von Mitglied",
                    ),
                ),
                (
                    "to_allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_to",
                        to="booking.allocation",
                        verbose_name="Gewünschte Buchung",
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_received",
                        to="booking.member",
                        verbose_name="An Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wechselwunsch",
                "verbose_name_plural": "Wechselwünsche",
                "ordering": ["-created_at"],
            },
        ),
    ]
