# Generated by Django 5.1.15 on 2026-06-22 11:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    """Jedes bestehende Mitglied wird zum Voll-Mitglied: erhält einen eigenen
    Mitglieds-Anteil mit dem bisherigen Tagebudget als Gesamt- und Eigenanteil."""
    Membership = apps.get_model("booking", "Membership")
    Member = apps.get_model("booking", "Member")
    jan1 = datetime.date(datetime.date.today().year, 1, 1)
    for m in Member.objects.all():
        ms = Membership.objects.create(
            label=m.display_name,
            annual_night_budget=m.annual_night_budget,
            created_on=jan1,
        )
        m.membership = ms
        m.save(update_fields=["membership"])


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_swaprequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eg_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Vielleben eG-Nummer"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Bezeichnung"
                    ),
                ),
                (
                    "annual_night_budget",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Gesamtkontingent des Anteils; wird auf die Nutzer aufgeteilt.",
                        verbose_name="Tage/Jahr (gesamt)",
                    ),
                ),
                (
                    "created_on",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Angelegt am"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitglieds-Anteil",
                "verbose_name_plural": "Mitglieds-Anteile",
                "ordering": ["eg_number", "label"],
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="annual_night_budget",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Fester Tage-Anteil dieses Nutzers am Anteil-Gesamtbudget.",
                verbose_name="Nächte/Jahr (Anteil)",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="booking.membership",
                verbose_name="Mitglieds-Anteil",
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
