# Generated by Django 5.1.15 on 2026-06-22 12:08 (Operationen umsortiert +
# Daten-Migration: Member.membership/Budget -> Share, bevor die Felder entfernt
# werden; Art (Voll/Teil) je Anteil aus der Nutzerzahl abgeleitet).

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Member = apps.get_model("booking", "Member")
    Membership = apps.get_model("booking", "Membership")
    Share = apps.get_model("booking", "Share")
    for m in Member.objects.all():
        if not m.membership_id:
            continue
        Share.objects.get_or_create(
            membership_id=m.membership_id, member_id=m.id,
            defaults=dict(
                night_budget=m.annual_night_budget or 0,
                wish_night_budget=m.wish_night_budget or 0,
            ),
        )
    for ms in Membership.objects.all():
        n = Share.objects.filter(membership_id=ms.id).count()
        ms.kind = "teil" if n > 1 else "voll"
        ms.save(update_fields=["kind"])


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_membership_alter_member_annual_night_budget_and_more"),
    ]

    operations = [
        # 1) Neue Felder + Share-Modell anlegen
        migrations.AddField(
            model_name="membership",
            name="kind",
            field=models.CharField(
                choices=[("voll", "Voll-Mitglied"), ("teil", "Teil-Mitglied (Tandem)")],
                default="voll", max_length=4, verbose_name="Art",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="wish_night_budget",
            field=models.PositiveIntegerField(
                default=25, verbose_name="Wunsch-Tage (gesamt)"
            ),
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name="ID")),
                ("night_budget", models.PositiveIntegerField(
                    default=0, verbose_name="Tage-Anteil")),
                ("wish_night_budget", models.PositiveIntegerField(
                    default=0, verbose_name="Wunsch-Tage-Anteil")),
                ("member", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name="shares",
                    to="booking.member", verbose_name="Nutzer")),
                ("membership", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name="shares",
                    to="booking.membership", verbose_name="Mitglieds-Anteil")),
            ],
            options={
                "verbose_name": "Tage-Anteil",
                "verbose_name_plural": "Tage-Anteile",
                "unique_together": {("membership", "member")},
            },
        ),
        # 2) Bestehende Zuordnungen/Budgets nach Share überführen
        migrations.RunPython(forwards, migrations.RunPython.noop),
        # 3) Alte Felder am Member entfernen
        migrations.RemoveField(model_name="member", name="annual_night_budget"),
        migrations.RemoveField(model_name="member", name="membership"),
        migrations.RemoveField(model_name="member", name="wish_night_budget"),
        # 4) Meta-Optionen anpassen
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["display_name"], "verbose_name": "Nutzer-Konto",
                     "verbose_name_plural": "Nutzer-Konten"},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"ordering": ["eg_number", "label"],
                     "verbose_name": "Mitglied (Anteil)",
                     "verbose_name_plural": "Mitglieder (Anteile)"},
        ),
    ]
