# Generated by Django 5.1.15 on 2026-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_alter_member_options_alter_membership_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="draw_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Terminierte Auslosung; läuft per Cron automatisch (siehe Management-Kommando run_due_lotteries).",
                null=True,
                verbose_name="Losung am",
            ),
        ),
    ]
