# Generated by Django 5.1.15 on 2026-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_bookingperiod_draw_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="member",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AddField(
            model_name="member",
            name="legal_name",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Vollständiger Name"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="membership_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Mitgliedsnummer (optional)"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="street",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Straße & Nr."
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
        ),
    ]
