# Generated by Django 5.1.15 on 2026-06-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_member_city_member_iban_member_legal_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["eg_number", "label"],
                "verbose_name": "Mitglieds-Anteil",
                "verbose_name_plural": "Mitglieds-Anteile",
            },
        ),
    ]
