# Generated by Django 5.1.15 on 2026-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_alter_membership_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="detail",
            field=models.TextField(blank=True, verbose_name="Details"),
        ),
    ]
