# Generated by Django 5.1.15 on 2026-06-22 14:50

from django.db import migrations, models


def dedup_target_year(apps, schema_editor):
    """Bevor `target_year` eindeutig wird: pro Jahr nur EINE Periode behalten.
    Ältere Datenbestände konnten mehrere Perioden je Jahr haben (z.B. eine
    globale + eine quartiersspezifische). Bevorzugt bleibt die zur freien
    Buchung freigegebene Periode erhalten, sonst die älteste; der Rest wird
    entfernt. Ohne Duplikate ist das ein No-Op."""
    BookingPeriod = apps.get_model("booking", "BookingPeriod")
    by_year = {}
    for p in BookingPeriod.objects.order_by("id"):
        by_year.setdefault(p.target_year, []).append(p)
    for periods in by_year.values():
        if len(periods) < 2:
            continue
        keep = next((p for p in periods if p.status == "free_booking"), periods[0])
        for p in periods:
            if p.pk != keep.pk:
                p.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_notification_detail"),
    ]

    operations = [
        # Zuerst evtl. vorhandene Duplikate je Jahr auflösen, sonst scheitert
        # der Unique-Index auf target_year (war die Ursache des 502).
        migrations.RunPython(dedup_target_year, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="bookingperiod",
            options={
                "ordering": ["-target_year"],
                "verbose_name": "Buchungsperiode (Jahr)",
                "verbose_name_plural": "Buchungsperioden (je Jahr eine)",
            },
        ),
        migrations.RemoveField(
            model_name="bookingperiod",
            name="applies_to_all",
        ),
        migrations.RemoveField(
            model_name="bookingperiod",
            name="quarters",
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="start",
            field=models.DateField(
                help_text="Ab wann der Zeitraum frei bebuchbar ist (darf vor dem 1.1. des Buchungsjahres liegen).",
                verbose_name="Zeitraum buchbar ab",
            ),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="target_year",
            field=models.PositiveIntegerField(unique=True, verbose_name="Buchungsjahr"),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="wishlist_close",
            field=models.DateField(blank=True, null=True, verbose_name="Wünsche bis"),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="wishlist_open",
            field=models.DateField(blank=True, null=True, verbose_name="Wünsche ab"),
        ),
    ]
