# Generated by Django 5.1.15 on 2026-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_notification_detail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingperiod",
            options={
                "ordering": ["-target_year"],
                "verbose_name": "Buchungsperiode (Jahr)",
                "verbose_name_plural": "Buchungsperioden (je Jahr eine)",
            },
        ),
        migrations.RemoveField(
            model_name="bookingperiod",
            name="applies_to_all",
        ),
        migrations.RemoveField(
            model_name="bookingperiod",
            name="quarters",
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="start",
            field=models.DateField(
                help_text="Ab wann der Zeitraum frei bebuchbar ist (darf vor dem 1.1. des Buchungsjahres liegen).",
                verbose_name="Zeitraum buchbar ab",
            ),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="target_year",
            field=models.PositiveIntegerField(unique=True, verbose_name="Buchungsjahr"),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="wishlist_close",
            field=models.DateField(blank=True, null=True, verbose_name="Wünsche bis"),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="wishlist_open",
            field=models.DateField(blank=True, null=True, verbose_name="Wünsche ab"),
        ),
    ]
