# Generated by Django 5.1.15 on 2026-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_bookingperiod_one_per_year"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["quarter", "start", "end"],
                name="booking_all_quarter_3666cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["start", "end"], name="booking_all_start_94c73c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["member", "start"], name="booking_all_member__be94a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["member", "read"], name="booking_not_member__d68861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(
                fields=["quarter", "fulfilled"], name="booking_wai_quarter_222b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wish",
            index=models.Index(
                fields=["period", "submitted"], name="booking_wis_period__2492ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wish",
            index=models.Index(
                fields=["member", "period"], name="booking_wis_member__d2fac3_idx"
            ),
        ),
    ]
