# Generated by Django 5.1.15 on 2026-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_allocation_booking_all_quarter_3666cd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="companions",
            field=models.CharField(
                blank=True,
                help_text="Mit wem reise ich an (frei eintragbar).",
                max_length=255,
                verbose_name="Begleitung",
            ),
        ),
    ]
