# Generated by Django 5.1.15 on 2026-06-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_allocation_companions"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email_opt_in",
            field=models.BooleanField(
                default=True,
                help_text="Wenn aus, bekommt das Mitglied keine E-Mails (In-App-Hinweise bleiben).",
                verbose_name="E-Mail-Benachrichtigungen",
            ),
        ),
        migrations.CreateModel(
            name="OutboxEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(max_length=254, verbose_name="Empfänger"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Betreff")),
                ("body", models.TextField(verbose_name="Text")),
                ("html_body", models.TextField(blank=True, verbose_name="HTML")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Versendet am"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Versuche"),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Letzter Fehler"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-Mail (Ausgang)",
                "verbose_name_plural": "E-Mails (Ausgang)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sent_at", "attempts"],
                        name="booking_out_sent_at_eac8da_idx",
                    )
                ],
            },
        ),
    ]
