# Generated by Django 5.1.15 on 2026-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_member_email_opt_in_outboxemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_emails",
                    models.CharField(
                        blank=True,
                        help_text="Komma-getrennt. Empfänger der Übersicht über anstehende Buchungen.",
                        max_length=400,
                        verbose_name="Verwaltung – E-Mail(s)",
                    ),
                ),
                (
                    "cleaning_emails",
                    models.CharField(
                        blank=True,
                        help_text="Komma-getrennt. Empfänger der Putzliste. Leer = wie Verwaltung.",
                        max_length=400,
                        verbose_name="Reinigungsteam – E-Mail(s)",
                    ),
                ),
                (
                    "notify_day",
                    models.PositiveSmallIntegerField(
                        default=25,
                        help_text="An diesem Tag des Monats geht die Übersicht der Buchungen des Folgemonats automatisch an die Verwaltung.",
                        verbose_name="Monats-Mail am Tag",
                    ),
                ),
                (
                    "last_admin_notice",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Zuletzt benachrichtigt am",
                    ),
                ),
            ],
            options={
                "verbose_name": "Betriebs-Einstellungen",
                "verbose_name_plural": "Betriebs-Einstellungen",
            },
        ),
    ]
