# Generated by Django 5.1.15 on 2026-06-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_opsconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxemail",
            name="attachment",
            field=models.BinaryField(blank=True, null=True, verbose_name="Anhang"),
        ),
        migrations.AddField(
            model_name="outboxemail",
            name="attachment_mime",
            field=models.CharField(
                blank=True,
                default="application/octet-stream",
                max_length=80,
                verbose_name="Anhang-Typ",
            ),
        ),
        migrations.AddField(
            model_name="outboxemail",
            name="attachment_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Anhang-Dateiname"
            ),
        ),
    ]
