# Generated by Django 5.1.15 on 2026-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_outboxemail_attachment_outboxemail_attachment_mime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="provisional",
            field=models.BooleanField(
                default=False, verbose_name="Vorläufig (unbestätigt)"
            ),
        ),
        migrations.AddField(
            model_name="lotteryrun",
            name="confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Bestätigt/veröffentlicht"
            ),
        ),
        migrations.AddField(
            model_name="lotteryrun",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bestätigt am"
            ),
        ),
        migrations.AddField(
            model_name="lotteryrun",
            name="karma_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Karma vor dem Lauf"
            ),
        ),
        migrations.AddField(
            model_name="lotteryrun",
            name="notices",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Vorbereitete Benachrichtigungen"
            ),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("wishes_open", "Für Wunsch-Einträge freigegeben"),
                    ("lottery_ready", "Zur Auslosung freigegeben"),
                    ("lottery_review", "Auslosung zur Prüfung (unbestätigt)"),
                    ("lottery_done", "Auslosung bestätigt/veröffentlicht"),
                    ("free_booking", "Freie Bebuchbarkeit innerhalb Zeitraum"),
                    ("ended", "Beendet"),
                    ("suspended", "Unterbrochen"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
