# Generated by Django 5.1.15 on 2026-06-23 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_allocation_provisional_lotteryrun_confirmed_and_more"),
        ("shop", "0007_bankimport_banktransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Globaler Schalter. Aus = externe Buchung gesperrt.",
                        verbose_name="Buchung für Externe aktiv",
                    ),
                ),
                (
                    "allowed_weekdays",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Komma-getrennt 0=Mo … 6=So. Jede Nacht muss auf einen dieser Wochentage fallen. Beispiel „0,1,2,3“ = Mo–Do (Anreise So–Mi, Abreise bis Do). Leer = alle Wochentage.",
                        max_length=20,
                        verbose_name="Erlaubte Übernachtungs-Wochentage",
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Mindestnächte"
                    ),
                ),
                (
                    "max_nights",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Höchstnächte (0 = unbegrenzt)"
                    ),
                ),
                (
                    "lead_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Frühestens so viele Tage vor Anreise buchbar.",
                        verbose_name="Vorlauf (Tage)",
                    ),
                ),
                (
                    "horizon_days",
                    models.PositiveSmallIntegerField(
                        default=365, verbose_name="Vorausbuchung (Tage, 0 = unbegrenzt)"
                    ),
                ),
                (
                    "cleaning_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Endreinigung (brutto)",
                    ),
                ),
                (
                    "cleaning_vat",
                    models.PositiveSmallIntegerField(
                        default=19, verbose_name="MwSt Reinigung"
                    ),
                ),
                (
                    "stay_vat",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="MwSt Beherbergung"
                    ),
                ),
                (
                    "payment_term_days",
                    models.PositiveSmallIntegerField(
                        default=14, verbose_name="Zahlungsziel (Tage)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Externe-Gäste-Einstellungen",
                "verbose_name_plural": "Externe-Gäste-Einstellungen",
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Straße & Nr."
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=12, verbose_name="PLZ"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Ort"),
                ),
                (
                    "country",
                    models.CharField(default="DE", max_length=2, verbose_name="Land"),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Verwaltungs-Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
            ],
            options={
                "verbose_name": "Externer Gast",
                "verbose_name_plural": "Externe Gäste",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quarter",
            name="external_bookable",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiv, können externe Gäste dieses Quartier (im Rahmen der Externen-Regeln) buchen.",
                verbose_name="Für externe Gäste buchbar",
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bruttopreis pro Nacht für externe Gäste (Beherbergung, 7 % USt).",
                max_digits=8,
                verbose_name="Preis/Nacht für Externe (brutto)",
            ),
        ),
        migrations.CreateModel(
            name="ExternalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(verbose_name="Anreise")),
                ("end", models.DateField(verbose_name="Abreise (exkl.)")),
                (
                    "persons",
                    models.PositiveIntegerField(default=1, verbose_name="Personen"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Reserviert (Zahlung offen)"),
                            ("confirmed", "Bestätigt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="confirmed",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Betrag (brutto)",
                    ),
                ),
                (
                    "hold_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reservierung gültig bis"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bestätigt am"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Storniert am"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_booking",
                        to="shop.invoice",
                        verbose_name="Rechnung",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_bookings",
                        to="booking.quarter",
                        verbose_name="Quartier",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.guest",
                        verbose_name="Gast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Externe Buchung",
                "verbose_name_plural": "Externe Buchungen",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["quarter", "start", "end"],
                        name="booking_ext_quarter_99cf82_idx",
                    ),
                    models.Index(
                        fields=["status", "start"], name="booking_ext_status_0586bd_idx"
                    ),
                ],
            },
        ),
    ]
