# Generated by Django 5.1.15 on 2026-06-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_externalconfig_guest_quarter_external_bookable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalconfig",
            name="deposit_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Anteil des Gesamtbetrags, der als Anzahlung fällig ist.",
                verbose_name="Anzahlung in % (0 = keine)",
            ),
        ),
        migrations.AddField(
            model_name="externalconfig",
            name="free_cancel_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Bis so viele Tage vor Anreise volle Erstattung.",
                verbose_name="Kostenlose Stornofrist (Tage vor Anreise)",
            ),
        ),
        migrations.AddField(
            model_name="externalconfig",
            name="late_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pauschale bei verspäteter Zahlung (mit der Mahnung fällig).",
                max_digits=8,
                verbose_name="Säumniszuschlag (brutto)",
            ),
        ),
        migrations.AddField(
            model_name="externalconfig",
            name="partial_cancel_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Bis so viele Tage vor Anreise teilweise Erstattung.",
                verbose_name="Teil-Storno-Frist (Tage vor Anreise)",
            ),
        ),
        migrations.AddField(
            model_name="externalconfig",
            name="partial_refund_percent",
            field=models.PositiveSmallIntegerField(
                default=50, verbose_name="Erstattung im Teil-Storno-Fenster (%)"
            ),
        ),
        migrations.AddField(
            model_name="externalconfig",
            name="terms",
            field=models.TextField(
                blank=True,
                help_text="Wird Gästen bei der Buchung und im Magic-Link angezeigt. Leer = aus den Fristen automatisch erzeugter Text.",
                verbose_name="Stornobedingungen (Anzeigetext)",
            ),
        ),
        migrations.CreateModel(
            name="QuarterPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="z. B. „Hochsaison“ (nur zur Anzeige).",
                        max_length=80,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(verbose_name="Von (Monat)"),
                ),
                (
                    "start_day",
                    models.PositiveSmallIntegerField(verbose_name="Von (Tag)"),
                ),
                (
                    "end_month",
                    models.PositiveSmallIntegerField(
                        verbose_name="Bis einschl. (Monat)"
                    ),
                ),
                (
                    "end_day",
                    models.PositiveSmallIntegerField(verbose_name="Bis einschl. (Tag)"),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bruttopreis pro Nacht in diesem Zeitraum (Beherbergung, 7 % USt).",
                        max_digits=8,
                        verbose_name="Preis/Nacht (brutto)",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="booking.quarter",
                        verbose_name="Quartier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saisonpreis",
                "verbose_name_plural": "Saisonpreise",
                "ordering": ["quarter", "start_month", "start_day"],
            },
        ),
    ]
