# Generated by Django 5.1.15 on 2026-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0025_externalconfig_deposit_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FairnessSimConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_users",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Anzahl gleich gestellter Parteien (alle Karma 1,0).",
                        verbose_name="Nutzer (gleich gestellt)",
                    ),
                ),
                (
                    "n_items",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Anzahl umkämpfter Quartiere im selben Zeitraum (Knappheit M < Nutzer). Jeder Nutzer wünscht alle.",
                        verbose_name="Knappe Quartiere / Wünsche je Nutzer",
                    ),
                ),
                (
                    "n_runs",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Wie viele Ziehungen mit unterschiedlichem Seed gemittelt werden (mehr = engere Konfidenzintervalle).",
                        verbose_name="Anzahl Lose-Durchläufe",
                    ),
                ),
                (
                    "last_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Letztes Ergebnis"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt berechnet"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fairness-Nachweis",
                "verbose_name_plural": "Fairness-Nachweis",
            },
        ),
    ]
