# Generated by Django 5.1.15 on 2026-06-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0027_verwaltung_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beds24Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hochgeladen am"
                    ),
                ),
                (
                    "filename",
                    models.CharField(blank=True, max_length=200, verbose_name="Datei"),
                ),
                (
                    "n_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Zeilen gesamt"
                    ),
                ),
                (
                    "n_imported",
                    models.PositiveIntegerField(default=0, verbose_name="Übernommen"),
                ),
            ],
            options={
                "verbose_name": "Beds24-Import",
                "verbose_name_plural": "Beds24-Importe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="allocation",
            name="source",
            field=models.CharField(
                choices=[
                    ("lottery", "Losung"),
                    ("spontaneous", "Spontanbuchung"),
                    ("external", "Externe Buchung"),
                    ("import", "Beds24-Import"),
                ],
                max_length=12,
                verbose_name="Quelle",
            ),
        ),
        migrations.CreateModel(
            name="Beds24ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=200, verbose_name="Gastname (Beds24)"),
                ),
                (
                    "arrival",
                    models.DateField(blank=True, null=True, verbose_name="Anreise"),
                ),
                (
                    "departure",
                    models.DateField(blank=True, null=True, verbose_name="Abreise"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Unit/Quartier (Beds24)",
                    ),
                ),
                (
                    "persons",
                    models.PositiveIntegerField(default=1, verbose_name="Personen"),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Referenz"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Originalzeile"
                    ),
                ),
                (
                    "suggested_score",
                    models.FloatField(default=0.0, verbose_name="Treffergüte"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("imported", "Übernommen"),
                            ("skipped", "Übersprungen"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hinweis"
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="booking.allocation",
                        verbose_name="Erzeugte Buchung",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="booking.beds24import",
                        verbose_name="Import",
                    ),
                ),
                (
                    "chosen_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "chosen_quarter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="booking.quarter",
                        verbose_name="Quartier",
                    ),
                ),
                (
                    "suggested_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="booking.member",
                        verbose_name="Vorschlag Mitglied",
                    ),
                ),
                (
                    "suggested_quarter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="booking.quarter",
                        verbose_name="Vorschlag Quartier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beds24-Buchungszeile",
                "verbose_name_plural": "Beds24-Buchungszeilen",
                "ordering": ["arrival", "id"],
            },
        ),
    ]
