# Generated by Django 5.1.15 on 2026-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0028_beds24import_alter_allocation_source_beds24importrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="opsconfig",
            name="beds24_import_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Der Beds24-Migrations-Assistent wird i. d. R. nur EINMALIG gebraucht. Nach dem Umzug hier ausschalten, dann ist er im Dashboard ausgeblendet und gesperrt.",
                verbose_name="Beds24-Import anzeigen",
            ),
        ),
    ]
