# Generated by Django 5.1.15 on 2026-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0029_opsconfig_beds24_import_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotteryrun",
            name="n_allocations",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Erfüllte Wünsche (Zuteilungen)"
            ),
        ),
        migrations.AddField(
            model_name="lotteryrun",
            name="n_losses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nicht erfüllte Wünsche (Verluste)"
            ),
        ),
    ]
