# Generated by Django 5.1.15 on 2026-06-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0030_lotteryrun_n_allocations_lotteryrun_n_losses"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalconfig",
            name="min_nights_follow_internal",
            field=models.BooleanField(
                default=True,
                help_text="An (Standard): Externe haben denselben Mindestaufenthalt wie Mitglieder – inkl. Saison-Mindestnächte (z. B. 7 im Sommer). Aus: stattdessen gilt der eigene feste Wert unten.",
                verbose_name="Mindestaufenthalt wie intern",
            ),
        ),
        migrations.AlterField(
            model_name="externalconfig",
            name="min_nights",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Nur wirksam, wenn „Mindestaufenthalt wie intern“ AUS ist. Darf von den internen Vorgaben abweichen (höher oder niedriger; ohne Saison-Verschärfung).",
                verbose_name="Eigener Mindestaufenthalt (Nächte)",
            ),
        ),
    ]
