# Generated by Django 5.1.15 on 2026-06-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0031_externalconfig_min_nights_follow_internal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="membership_number",
        ),
    ]
