# Generated by Django 5.1.15 on 2026-06-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0032_remove_member_membership_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.TextField(unique=True, verbose_name="Endpoint")),
                (
                    "p256dh",
                    models.CharField(max_length=200, verbose_name="Schlüssel (p256dh)"),
                ),
                ("auth", models.CharField(max_length=100, verbose_name="Auth-Secret")),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Gerät/Browser"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push-Abo",
                "verbose_name_plural": "Push-Abos",
                "ordering": ["-created_at"],
            },
        ),
    ]
