# Generated by Django 5.1.15 on 2026-06-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0033_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="beds24importrow",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-Mail (Beds24)"
            ),
        ),
    ]
