# Generated by Django 5.1.15 on 2026-06-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0034_beds24importrow_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="beds24importrow",
            name="match_kind",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Treffer-Art"
            ),
        ),
    ]
