# Generated by Django 5.1.15 on 2026-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0035_beds24importrow_match_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Schaltet den Vor-Ort-Terminal-Modus frei. Aus = Roster/Sync verweigert.",
                        verbose_name="Terminal aktiv",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        help_text="Langes Geheimnis, das im Terminal-Gerät hinterlegt wird. Bei Verlust/Diebstahl neu erzeugen (Aktion im Backend).",
                        max_length=64,
                        verbose_name="Geräte-Token",
                    ),
                ),
                (
                    "idle_timeout_seconds",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Nach so vielen Sekunden ohne Aktion wird am Terminal automatisch abgemeldet.",
                        verbose_name="Auto-Abmeldung nach (Sekunden)",
                    ),
                ),
                (
                    "max_pin_attempts",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="PIN-Sperre nach Fehlversuchen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hofladen-Terminal-Einstellungen",
                "verbose_name_plural": "Hofladen-Terminal-Einstellungen",
            },
        ),
        migrations.AddField(
            model_name="member",
            name="terminal_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Hofladen-Terminal erlaubt"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="terminal_pin",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Terminal-PIN (gehasht)"
            ),
        ),
    ]
