# Generated by Django 5.1.15 on 2026-06-27 19:04

from django.db import migrations, models


def enable_for_existing(apps, schema_editor):
    """Terminal ist jetzt standardmäßig an – auch für bereits bestehende Konten.
    (Aktiv am Terminal wird man trotzdem erst mit selbst gesetzter PIN.)"""
    apps.get_model("booking", "Member").objects.update(terminal_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0036_terminalconfig_member_terminal_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="terminal_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Hofladen-Terminal erlaubt"
            ),
        ),
        migrations.RunPython(enable_for_existing, migrations.RunPython.noop),
    ]
