# Generated by Django 5.1.15 on 2026-06-28 06:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("booking", "0037_alter_member_terminal_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[],
            options={
                "verbose_name": "Neuer Benutzer (Zuordnung)",
                "verbose_name_plural": "Neue Benutzer (Zuordnung)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
