# Generated by Django 5.2.15 on 2026-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0038_pendinguser"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="seed_commit",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Seed-Prüfsumme (SHA-256)"
            ),
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="seed_committed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Prüfsumme veröffentlicht am"
            ),
        ),
    ]
