# Generated by Django 5.2.15 on 2026-06-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0039_bookingperiod_seed_commit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nighttransfer",
            name="thanked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bedankt am"
            ),
        ),
    ]
