# Generated by Django 5.2.15 on 2026-06-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0040_nighttransfer_thanked_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayPoolEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Jahr")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("donate", "Spende in den Pool"),
                            ("withdraw", "Entnahme aus dem Pool"),
                        ],
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                ("nights", models.PositiveIntegerField(verbose_name="Tage")),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_entries",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tage-Pool-Buchung",
                "verbose_name_plural": "Tage-Pool-Buchungen",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["year", "kind"], name="booking_day_year_44d76d_idx"
                    )
                ],
            },
        ),
    ]
