# Generated by Django 5.2.15 on 2026-06-28 20:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_membership(apps, schema_editor):
    """Bestehende Buchungen/Wünsche dem Mitglieds-Anteil zurechnen – aber NUR,
    wenn der Nutzer genau EINEM Anteil angehört (eindeutig). Bei Mehrfach-Tandem
    bleibt die Zuordnung leer (kann nachträglich nicht sicher erraten werden); neue
    Buchungen/Wünsche setzen den Anteil immer explizit (ADR 0066)."""
    Share = apps.get_model("booking", "Share")
    Allocation = apps.get_model("booking", "Allocation")
    Wish = apps.get_model("booking", "Wish")

    # member_id -> eindeutiger membership_id (None, wenn 0 oder >1 Anteile)
    sole = {}
    for member_id, membership_id in Share.objects.values_list("member_id", "membership_id"):
        if member_id in sole:
            sole[member_id] = None          # mehr als ein Anteil -> nicht eindeutig
        else:
            sole[member_id] = membership_id
    sole = {mid: ms for mid, ms in sole.items() if ms is not None}

    for model in (Allocation, Wish):
        updates = []
        for obj in model.objects.filter(membership__isnull=True).only("id", "member_id"):
            ms = sole.get(obj.member_id)
            if ms is not None:
                obj.membership_id = ms
                updates.append(obj)
        if updates:
            model.objects.bulk_update(updates, ["membership"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0041_daypoolentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="booking.membership",
                verbose_name="Mitglieds-Anteil",
            ),
        ),
        migrations.AddField(
            model_name="wish",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wishes",
                to="booking.membership",
                verbose_name="Mitglieds-Anteil",
            ),
        ),
        migrations.RunPython(backfill_membership, migrations.RunPython.noop),
    ]
