# Generated by Django 5.2.15 on 2026-06-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0042_allocation_wish_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="allow_gap_fill",
            field=models.BooleanField(
                default=True,
                help_text="Füllt eine Buchung eine freie Lücke vollständig aus (schließt beidseitig an Belegungen/Zeitraum-Grenzen an), entfällt die Mindestnächte-Regel und die Vorausfrist.",
                verbose_name="Lücken unter Mindestnächte füllen",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="group_min_persons",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Ab dieser Personenzahl gilt eine Buchung als Gruppe – dann werden Gruppen-Wohneinheiten (z. B. Stallgebäude) zuerst angezeigt. Nur Reihenfolge/Hinweis, keine Sperre.",
                verbose_name="Gruppe ab Personen",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="min_lead_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Spontanbuchungen müssen mindestens so viele Tage vor der Anreise erfolgen. Lückenfüllende Buchungen sind ausgenommen. 0 = keine Frist.",
                verbose_name="Spontan-Vorausfrist (Tage)",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="winter_guideline_nights",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Orientierung (kein Limit): empfohlene Anzahl Tage im Winterhalbjahr Oktober–März, damit sich die Buchungen übers Jahr verteilen.",
                verbose_name="Richtwert Tage Oktober–März",
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="building",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Organisatorische Gruppierung, z. B. „Stallgebäude“ (nur Anzeige).",
                max_length=80,
                verbose_name="Gebäude",
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="prefer_for_groups",
            field=models.BooleanField(
                default=False,
                help_text="Diese Wohneinheit wird Gruppen (große Personenzahl) zuerst empfohlen – z. B. die Wohnungen des Stallgebäudes. Keine harte Sperre, nur Reihenfolge/Hinweis.",
                verbose_name="Für Gruppen zuerst anbieten",
            ),
        ),
    ]
