# Generated by Django 5.2.15 on 2026-06-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0043_bookingpolicy_allow_gap_fill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="allow_undersized_units",
            field=models.BooleanField(
                default=True,
                help_text="Erlaubt, eine Unterkunft auch für MEHR Personen zu buchen, als sie ausgelegt ist (z. B. wenn nichts Passendes mehr frei ist). Die Buchung wird dann deutlich als „kleiner als eure Gruppe“ gekennzeichnet.",
                verbose_name="Kleinere Unterkünfte zulassen",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="max_weekends_per_year",
            field=models.PositiveIntegerField(
                default=9,
                help_text="Orientierung (kein Limit): so viele Wochenenden je Mitglied und Jahr sind fair (bei voller Gemeinschaft). Beim Buchen wird ein Hinweis angezeigt, wenn man sich diesem Höchstwert nähert.",
                verbose_name="Richtwert HÖCHST-Wochenenden/Jahr",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpolicy",
            name="winter_guideline_nights",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Orientierung (kein Limit): so viele Tage sollten MINDESTENS ins Winterhalbjahr Okt–März fallen, damit sich die Buchungen übers Jahr verteilen. Gilt pro vollem Anteil (50 Tage); bei Teil-/Tandem-Anteilen anteilig weniger. Kein Maximum.",
                verbose_name="Richtwert MINDEST-Tage Okt–März (pro vollem Anteil)",
            ),
        ),
    ]
