# Generated by Django 5.2.15 on 2026-06-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0044_bookingpolicy_allow_undersized_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpolicy",
            name="allow_undersized_units",
            field=models.BooleanField(
                default=True,
                help_text="Erlaubt, eine Unterkunft auch für MEHR oder WENIGER Personen zu buchen, als sie ausgelegt ist (z. B. wenn nichts Passendes mehr frei ist). Die Buchung wird dann deutlich gekennzeichnet („kleiner als eure Gruppe“ bzw. „größer als nötig“).",
                verbose_name="Personenzahl außerhalb des Rahmens zulassen",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpolicy",
            name="group_min_persons",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Ab dieser Personenzahl gilt eine Buchung als Gruppe – dann werden Gruppen-Wohneinheiten (z. B. Stallgebäude) zuerst angezeigt. Nur Reihenfolge/Hinweis, keine Sperre.",
                verbose_name="Gruppe ab Personen",
            ),
        ),
    ]
