# Generated by Django 5.2.15 on 2026-07-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0045_alter_bookingpolicy_allow_undersized_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="max_wishes_per_period",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Obergrenze für die Anzahl der Wünsche, die ein Mitglied je Losungs-Periode eintragen darf. 0 = unbegrenzt (Standard – bewusst, damit Rückfall-Wünsche möglich bleiben). Nur setzen, wenn die Delegation eine Begrenzung beschließt (ADR 0078).",
                verbose_name="Max. Wünsche je Periode (0 = unbegrenzt)",
            ),
        ),
    ]
