# Generated by Django 5.2.15 on 2026-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0046_bookingpolicy_max_wishes_per_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="accept_swap_requests",
            field=models.BooleanField(
                default=True,
                help_text="Wenn aus, erscheint das Mitglied für andere nicht als Tausch-Partner und kann keine Tausch-Anfrage erhalten (ADR 0078). Die reine Anzeige „wer ist zur gleichen Zeit da“ bleibt.",
                verbose_name="Tausch-Anfragen erlauben",
            ),
        ),
    ]
