# Generated by Django 5.2.15 on 2026-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0047_member_accept_swap_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="wish_reminder1_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="1. Wunsch-Erinnerung versendet am"
            ),
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="wish_reminder2_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="2. Wunsch-Erinnerung versendet am"
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="wish_reminder_lead1",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="So viele Tage VOR dem Einreiche-Schluss (Losdatum) werden Mitglieder erinnert, die noch keinen Wunsch eingereicht haben. 0 = diese Stufe aus (ADR 0080).",
                verbose_name="1. Wunsch-Erinnerung (Tage vor Frist)",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="wish_reminder_lead2",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Zweite, dringlichere Erinnerung so viele Tage vor dem Schluss. Sollte kleiner als die erste sein. 0 = diese Stufe aus (ADR 0080).",
                verbose_name="2. Wunsch-Erinnerung (Tage vor Frist)",
            ),
        ),
    ]
