# Generated by Django 5.2.15 on 2026-07-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0048_bookingperiod_wish_reminder1_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quarter_name",
                    models.CharField(max_length=120, verbose_name="Quartier"),
                ),
                ("start", models.DateField(verbose_name="Anreise")),
                ("end", models.DateField(verbose_name="Abreise")),
                (
                    "persons",
                    models.PositiveIntegerField(default=1, verbose_name="Personen"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=12, verbose_name="Quelle"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Storniert am"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellations",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stornierte Buchung (Nachweis)",
                "verbose_name_plural": "Stornierte Buchungen (Nachweis)",
                "ordering": ["-cancelled_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "cancelled_at"],
                        name="booking_can_member__a932d0_idx",
                    )
                ],
            },
        ),
    ]
