# Generated by Django 5.2.15 on 2026-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0049_cancellationlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quarter",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Quartier",
                "verbose_name_plural": "Quartiere",
            },
        ),
        migrations.AddField(
            model_name="quarter",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Sortierung im Belegungsplan – kleiner = weiter oben (an beds24 angelehnt). Gleiche Werte werden alphabetisch gereiht.",
                verbose_name="Reihenfolge (Belegungsplan)",
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="target_occupancy",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optionale Zielauslastung in Prozent. Ist sie gesetzt, zeigt das Dashboard je Quartier eine Ampel (🔴/🟡/🟢). Leer = keine Ampel.",
                null=True,
                verbose_name="Ziel-Auslastung (%)",
            ),
        ),
    ]
