# Generated by Django 5.2.15 on 2026-07-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0050_alter_quarter_options_quarter_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="er_decision_lock_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Die Betriebsleitung kann eine Endreinigungs-Entscheidung (bestätigt/abgelehnt) bis zu so viele Tage VOR der Anreise noch ändern; danach ist sie fest, damit sich das Mitglied darauf einstellen kann. 0 = jederzeit änderbar (kein Lock). ADR 0081.",
                verbose_name="Endreinigung: Frist zum Revidieren (Tage vor Anreise)",
            ),
        ),
    ]
