# Generated by Django 5.2.15 on 2026-07-04 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0051_bookingpolicy_er_decision_lock_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarterBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(verbose_name="Von (Anreisesperre ab)")),
                (
                    "end",
                    models.DateField(
                        verbose_name="Bis (exklusiv – erster wieder freier Tag)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="z. B. Renovierung, Wasserschaden, Grundreinigung.",
                        max_length=200,
                        verbose_name="Grund",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="booking.quarter",
                        verbose_name="Quartier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sperrzeit (Reinigung/Reparatur)",
                "verbose_name_plural": "Sperrzeiten (Reinigung/Reparatur)",
                "ordering": ["start", "quarter__sort_order"],
                "indexes": [
                    models.Index(
                        fields=["quarter", "start", "end"],
                        name="booking_qua_quarter_b5fe29_idx",
                    )
                ],
            },
        ),
    ]
