# Generated by Django 5.2.15 on 2026-07-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0052_quarterblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="internal_note",
            field=models.CharField(
                blank=True,
                help_text="Nur für Betriebsleitung/Team – wird dem Mitglied NICHT angezeigt (#84).",
                max_length=500,
                verbose_name="Interne Notiz (nur Team/BL)",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="special_requests",
            field=models.CharField(
                blank=True,
                help_text="Optional: Hund, Kinder, Zustellbett o. Ä. – für die Vorbereitung durch das Team (#62/#68).",
                max_length=255,
                verbose_name="Besonderheiten",
            ),
        ),
    ]
