# Generated by Django 5.2.15 on 2026-07-05 08:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("booking", "0053_allocation_internal_note_allocation_special_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rolle",
            fields=[],
            options={
                "verbose_name": "Rolle",
                "verbose_name_plural": "Rollen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="excluded_from",
            field=models.DateField(
                blank=True,
                help_text="Ab diesem Datum ist das Konto deaktiviert (Login aus). Bestehende Buchungen nach diesem Datum müssen vorher gelöst werden.",
                null=True,
                verbose_name="Ausgeschieden ab",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="passive_from",
            field=models.DateField(
                blank=True,
                help_text="Ab diesem Datum kann das Mitglied nicht mehr buchen (Hofladen/Login bleiben). Leer = aktiv.",
                null=True,
                verbose_name="Passiv ab",
            ),
        ),
    ]
