# Generated by Django 5.2.15 on 2026-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0054_rolle_member_excluded_from_member_passive_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Für Rückfragen der Betriebsleitung (im Profil selbst änderbar).",
                max_length=40,
                verbose_name="Telefon",
            ),
        ),
    ]
