# Generated by Django 5.2.15 on 2026-07-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0055_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="short_notice_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Storniert oder verkürzt ein Mitglied eine Buchung, deren Anreise höchstens so viele Tage entfernt ist, VERFALLEN die betroffenen Tage – außer ein anderes Mitglied bucht den frei gewordenen Zeitraum (ganz/teilweise) neu. Alle Mitglieder werden dann in der App informiert (ohne Mail). Bei mehr Vorlauf gibt es die Tage normal zurück. ADR 0088.",
                verbose_name="Kurzfrist-Grenze für Storno/Verkürzen (Tage vor Anreise)",
            ),
        ),
        migrations.CreateModel(
            name="ForfeitedNights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Jahr")),
                ("start", models.DateField(verbose_name="Von")),
                ("end", models.DateField(verbose_name="Bis (exkl.)")),
                (
                    "nights",
                    models.PositiveIntegerField(verbose_name="Verwirkte Nächte"),
                ),
                (
                    "reason",
                    models.CharField(
                        default="cancel",
                        help_text="cancel = Storno · shorten = Verkürzung",
                        max_length=20,
                        verbose_name="Anlass",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forfeits",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forfeits",
                        to="booking.quarter",
                        verbose_name="Quartier (frei geworden)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurzfrist-Verwirkung (Tage)",
                "verbose_name_plural": "Kurzfrist-Verwirkungen (Tage)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "year"], name="booking_for_member__8d0ca9_idx"
                    )
                ],
            },
        ),
    ]
