# Generated by Django 5.2.15 on 2026-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0056_bookingpolicy_short_notice_days_forfeitednights"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_key",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Ereignis"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "recipients",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        verbose_name="Empfänger (kommagetrennt, leer = Verwaltungs-Adressen)",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "sofort (bei jedem Ereignis)"),
                            ("event", "ereignisbezogen (mit Vorlauf)"),
                            ("daily", "täglich"),
                            ("weekly", "wöchentlich"),
                            ("monthly", "monatlich"),
                        ],
                        default="weekly",
                        max_length=10,
                        verbose_name="Frequenz",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        default=0,
                        verbose_name="Wochentag (0=Mo … 6=So, bei wöchentlich)",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Tag im Monat (bei monatlich)"
                    ),
                ),
                (
                    "attach_pdf",
                    models.BooleanField(
                        default=False, verbose_name="PDF anhängen (wo verfügbar)"
                    ),
                ),
                (
                    "lead_days",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Vorlauf (Tage)"
                    ),
                ),
                (
                    "last_run_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zuletzt gelaufen am"
                    ),
                ),
            ],
            options={
                "verbose_name": "Benachrichtigungs-Einstellung",
                "verbose_name_plural": "Benachrichtigungs-Einstellungen",
                "ordering": ["event_key"],
            },
        ),
    ]
