# Generated by Django 5.2.15 on 2026-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0057_notificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="bl_reminder_at",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Verwaltungs-Erinnerung (Losung steht an) am",
            ),
        ),
    ]
