# Generated by Django 5.2.15 on 2026-07-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0058_bookingperiod_bl_reminder_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="opsconfig",
            name="contact_email_bl",
            field=models.CharField(
                blank=True,
                help_text="Empfänger für Kontakt-Anliegen zu Buchung, Endreinigung, allgemeine Fragen. Leer = Verwaltungs-Adressen.",
                max_length=400,
                verbose_name="Kontakt – Buchung/Reinigung/Allgemein",
            ),
        ),
        migrations.AddField(
            model_name="opsconfig",
            name="contact_email_tech",
            field=models.CharField(
                blank=True,
                help_text="Empfänger für technische Probleme (Bug/App). Leer = Verwaltungs-Adressen.",
                max_length=400,
                verbose_name="Kontakt – App-Problem/Bug",
            ),
        ),
        migrations.AddField(
            model_name="outboxemail",
            name="reply_to",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Antwort an"
            ),
        ),
    ]
