# Generated by Django 5.2.15 on 2026-07-05 14:25

from django.db import migrations, models


def _exclude_zero_target(apps, schema_editor):
    """Bestandsdaten: Quartiere, die bisher über eine Ziel-Auslastung von **exakt 0 %**
    aus der Quote genommen wurden (der frühere Behelf), werden direkt auf
    count_in_occupancy=False gesetzt – so bleibt die gewohnte Auswertung erhalten
    (ADR 0096)."""
    Quarter = apps.get_model("booking", "Quarter")
    Quarter.objects.filter(target_occupancy=0).update(count_in_occupancy=False)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0060_allocation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarter",
            name="count_in_occupancy",
            field=models.BooleanField(
                default=True,
                help_text="Aus, wenn diese Fläche NICHT in die Auslastungs-Statistik zählen soll (z. B. Camping- oder Gemeinschaftsflächen). Buchbar bleibt sie trotzdem.",
                verbose_name="In Auslastungs-Quote einbeziehen",
            ),
        ),
        migrations.RunPython(_exclude_zero_target, migrations.RunPython.noop),
    ]
