# Generated by Django 5.2.15 on 2026-07-05 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0061_quarter_count_in_occupancy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="block_min_notice_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Eine Sperrzeit über eine bestehende Buchung ist regulär nur mit diesem Mindestvorlauf möglich (damit sich die Mitglieder darauf einlassen können). Startet die Sperrung früher, greift der **dringende** Workflow (Wasserrohrbruch o. Ä.) mit Umbuchung/Ausgleich. ADR 0097.",
                verbose_name="Sperrzeit: Vorlauf für Absprache mit Mitgliedern (Tage)",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="max_compensation_days",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Kann die Verwaltung bei einer dringenden Sperrung keine passende Ersatz-Unterkunft bereitstellen, darf sie dem Mitglied bis zu so viele zusätzliche Tage gutschreiben (je nach Schwere). ADR 0097.",
                verbose_name="Max. Ausgleichs-Tage bei dringender Sperrung",
            ),
        ),
        migrations.CreateModel(
            name="CompensationGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Jahr")),
                (
                    "days",
                    models.PositiveSmallIntegerField(verbose_name="Ausgleichs-Tage"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=300, verbose_name="Grund"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gewährt von",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensations",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ausgleichs-Tage",
                "verbose_name_plural": "Ausgleichs-Tage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RelocationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "undersized",
                    models.BooleanField(
                        default=False,
                        help_text="Die vorgeschlagene Unterkunft ist kleiner als die Personenzahl der Buchung – dem Mitglied wird das ausdrücklich mitgeteilt.",
                        verbose_name="Kleiner als die Gruppe",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Grund der Sperrung"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Vorgeschlagen"),
                            ("accepted", "Angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("cancelled", "Zurückgezogen"),
                        ],
                        default="proposed",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Beantwortet am"
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relocation_requests",
                        to="booking.allocation",
                        verbose_name="Betroffene Buchung",
                    ),
                ),
                (
                    "from_quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="booking.quarter",
                        verbose_name="Bisherige (gesperrte) Unterkunft",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relocation_requests",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "to_quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="booking.quarter",
                        verbose_name="Vorgeschlagene Unterkunft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umbuchungs-Anfrage",
                "verbose_name_plural": "Umbuchungs-Anfragen",
                "ordering": ["-created_at"],
            },
        ),
    ]
