# Generated by Django 5.2.15 on 2026-07-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0062_bookingpolicy_block_min_notice_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="pool_eligible_remaining",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Aus dem Solidaritäts-Pool darf ein Mitglied erst entnehmen, wenn sein Jahresbudget bis auf höchstens so viele Tage aufgebraucht ist (Bedarfs-Signal). ADR 0064/0099.",
                verbose_name="Solidaritäts-Pool: Entnahme erst ab Rest-Budget ≤",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="pool_withdraw_cap",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Mehr als so viele Tage darf ein Mitglied pro Jahr nicht aus dem Pool entnehmen. ADR 0064/0099.",
                verbose_name="Solidaritäts-Pool: Höchst-Entnahme je Mitglied/Jahr",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="pool_withdraw_from_month",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Optionaler Zeit-Riegel gegen „schnell verbrauchen, dann nachladen“: Entnahmen sind erst ab diesem Monat möglich (z. B. 9 = ab September). 0 = ganzjährig (kein Riegel). ADR 0099.",
                verbose_name="Solidaritäts-Pool: Entnahme erst ab Monat (1–12; 0 = ganzjährig)",
            ),
        ),
    ]
