# Generated by Django 5.2.15 on 2026-07-06 07:18

from django.db import migrations, models


def _default_to_september(apps, schema_editor):
    """Der Zeit-Riegel war in 0063 mit Default 0 (aus) eingeführt und noch nicht
    bewusst gesetzt – die Bestands-Singletons auf den neuen Default 9 (September)
    heben (ADR 0099). Bereits abweichend Konfiguriertes (≠ 0) bleibt unangetastet."""
    BookingPolicy = apps.get_model("booking", "BookingPolicy")
    BookingPolicy.objects.filter(pool_withdraw_from_month=0).update(
        pool_withdraw_from_month=9)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0063_bookingpolicy_pool_eligible_remaining_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpolicy",
            name="pool_withdraw_from_month",
            field=models.PositiveSmallIntegerField(
                default=9,
                help_text="Zeit-Riegel gegen „schnell verbrauchen, dann nachladen“: Entnahmen sind erst ab diesem Monat möglich (Default 9 = ab September). 0 = ganzjährig (kein Riegel). ADR 0099.",
                verbose_name="Solidaritäts-Pool: Entnahme erst ab Monat (1–12; 0 = ganzjährig)",
            ),
        ),
        migrations.RunPython(_default_to_september, migrations.RunPython.noop),
    ]
