# Generated by Django 5.2.15 on 2026-07-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0064_alter_bookingpolicy_pool_withdraw_from_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="guideline_basis",
            field=models.CharField(
                choices=[
                    ("member", "pro Mitglied (jede Person der volle Wert)"),
                    ("share", "pro vollem Anteil (Tandem/Trio anteilig nach Tagen)"),
                ],
                default="share",
                help_text="Bezugsgröße für die BEIDEN Richtwerte oben (Winter-Tage und Höchst-Wochenenden). „pro Mitglied“: jede Person bekommt den vollen Wert. „pro vollem Anteil“: der Wert gilt für einen vollen Anteil (50 Tage); wer nur einen Teil hält (Tandem/Trio), bekommt anteilig nach seinem Tage-Budget weniger. Reine Anzeige – kein Limit.",
                max_length=8,
                verbose_name="Richtwert-Berechnung (Winter & Wochenenden)",
            ),
        ),
    ]
