# Generated by Django 5.2.15 on 2026-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0065_bookingpolicy_guideline_basis"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerwaltungAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("access_buchungen", "Verwaltung: Buchungen/Reinigung/Sperrzeiten"),
                    (
                        "book_for_member",
                        "Verwaltung: Buchungen für Mitglieder anlegen/ändern",
                    ),
                    ("export_wishes", "Verwaltung: Wunsch-Export (Entzerrungsphase)"),
                    (
                        "add_wish_for_member",
                        "Verwaltung: Wunsch für Mitglied nachtragen",
                    ),
                    (
                        "access_mitglieder",
                        "Verwaltung: Mitglieder freischalten/zuordnen",
                    ),
                    ("access_quartiere", "Verwaltung: Quartiere/Sperrzeiten"),
                    ("access_rechnungen", "Verwaltung: Rechnungen/Kontoabgleich"),
                    ("access_hofladen", "Verwaltung: Hofladen-Katalog"),
                    ("send_broadcast", "Verwaltung: Rundnachricht senden"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
