# Generated by Django 5.2.15 on 2026-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0067_lotteryrun_retrospective"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="review_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Überschreibt für diese Periode die Länge der Entzerrungsphase (ADR 0101). Leer = Vorgabe aus den Buchungsrichtlinien.",
                null=True,
                verbose_name="Entzerrungsphase (Tage vor Losung)",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="review_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Länge der Entzerrungs-/Review-Phase VOR der Losung (ADR 0101): Ab „Losdatum − diese Tage“ ist die Einreiche-Frist vorbei (Teilnehmerkreis fest); Teilnehmer können ihre Wünsche noch anpassen und sehen die Nachfrage. Je Periode überschreibbar.",
                verbose_name="Entzerrungsphase (Tage vor der Losung)",
            ),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("wishes_open", "Für Wunsch-Einträge freigegeben"),
                    (
                        "wishes_review",
                        "Entzerrungsphase (Frist vorbei, anpassen möglich)",
                    ),
                    ("lottery_ready", "Zur Auslosung freigegeben"),
                    ("lottery_review", "Auslosung zur Prüfung (unbestätigt)"),
                    ("lottery_done", "Auslosung bestätigt/veröffentlicht"),
                    ("free_booking", "Freie Bebuchbarkeit innerhalb Zeitraum"),
                    ("ended", "Beendet"),
                    ("suspended", "Unterbrochen"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
