# Generated by Django 5.2.15 on 2026-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0068_bookingperiod_review_days_bookingpolicy_review_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="coordination_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="In der Entzerrungsphase vor der Losung sind Mitgliedern mit einem überlappenden Wunsch Name + Telefon sichtbar, damit sie sich privat absprechen können (Standard: sichtbar, ADR 0101). Wenn AN, erscheint dieses Mitglied dort NICHT (1-Klick-Opt-out im Profil).",
                verbose_name="Absprachen-Sichtbarkeit abgeschaltet",
            ),
        ),
    ]
