# Generated by Django 5.2.15 on 2026-07-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0070_wish_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="demand_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Nachfrage-Snapshots"
            ),
        ),
    ]
