# Generated by Django 5.2.15 on 2026-07-11 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0071_bookingperiod_demand_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="wish",
            name="booking_wis_period__2492ba_idx",
        ),
        migrations.RemoveField(
            model_name="wish",
            name="submitted",
        ),
        migrations.RemoveField(
            model_name="wish",
            name="submitted_at",
        ),
        migrations.AddField(
            model_name="wish",
            name="added_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aufgenommen am"
            ),
        ),
        migrations.AddIndex(
            model_name="wish",
            index=models.Index(
                fields=["period"], name="booking_wis_period__2ce4db_idx"
            ),
        ),
    ]
