# Generated by Django 5.2.15 on 2026-07-11 07:22

from django.db import migrations, models


def hide_both_channels_for_prior_opt_outs(apps, schema_editor):
    """Wer bisher komplett unsichtbar war (`coordination_opt_out=True`), soll seine
    Kontaktdaten weiter verbergen: beide Kanäle (Telefon + E-Mail) auf „verborgen".
    Der Name wird jetzt gezeigt (Begegnung, ADR 0101-Nachtrag Batch 2) – die zuvor
    verborgenen Kontaktkanäle bleiben es."""
    Member = apps.get_model("booking", "Member")
    Member.objects.filter(coordination_opt_out=True).update(
        coordination_hide_phone=True, coordination_hide_email=True)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0072_remove_wish_booking_wis_period__2492ba_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="coordination_hide_email",
            field=models.BooleanField(
                default=False,
                help_text="Wie oben, aber für die E-Mail-Adresse. Wenn AN, wird die E-Mail in der Entzerrungsphase NICHT gezeigt (der Name bleibt sichtbar).",
                verbose_name="E-Mail für Absprachen verbergen",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="coordination_hide_phone",
            field=models.BooleanField(
                default=False,
                help_text="In der Entzerrungsphase vor der Losung sehen Mitglieder mit einem überlappenden Wunsch Name + Kontakt, damit sie sich privat absprechen können (Standard: sichtbar, ADR 0101). Wenn AN, wird die Telefonnummer dort NICHT gezeigt (der Name bleibt sichtbar).",
                verbose_name="Telefon für Absprachen verbergen",
            ),
        ),
        migrations.RunPython(
            hide_both_channels_for_prior_opt_outs,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="member",
            name="coordination_opt_out",
        ),
    ]
