# Generated by Django 5.2.15 on 2026-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0073_remove_member_coordination_opt_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpolicy",
            name="review_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Länge der Entzerrungs-/Review-Phase VOR der Losung (ADR 0101): Ab „Losdatum − diese Tage“ beginnt die Entzerrungsphase; Mitglieder können ihre Wünsche noch anpassen und sehen die Nachfrage. Je Periode überschreibbar.",
                verbose_name="Entzerrungsphase (Tage vor der Losung)",
            ),
        ),
    ]
