# Generated by Django 5.2.15 on 2026-07-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0074_alter_bookingpolicy_review_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="details_pending",
            field=models.BooleanField(
                default=False,
                help_text="Los-Buchung, bei der das Mitglied Personen/Begleitung/Besonderheiten/Endreinigung noch ergänzen soll.",
                verbose_name="Details nachzutragen",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="details_reminded_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vervollständigung erinnert am"
            ),
        ),
    ]
