# Generated by Django 5.2.15 on 2026-07-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0075_allocation_details_pending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opsconfig",
            name="nl_learning_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Opt-in (ADR 0113): pseudonymisiert erfassen, welche Kurz-Eingaben der Parser nicht verstand und was die Person danach wählte, um Vorschläge (Aliase/Reihung) zur BESTÄTIGUNG anzubieten. Aus = es wird nichts gesammelt. Braucht zusätzlich das Env-Geheimnis NL_LEARN_SALT.",
                verbose_name="NL-Parser lernen lassen",
            ),
        ),
        migrations.CreateModel(
            name="NlInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erfasst"),
                ),
                (
                    "pseudonym",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Pseudonym (HMAC)"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("wish", "Wunsch"), ("booking", "Buchung")],
                        max_length=8,
                        verbose_name="Art",
                    ),
                ),
                (
                    "unresolved",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Nicht aufgelöste Tokens"
                    ),
                ),
                (
                    "proposed_quarter_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Vorschlag Quartier-ID"
                    ),
                ),
                (
                    "proposed_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Vorschlag Monat"
                    ),
                ),
                (
                    "suggestion_shown",
                    models.BooleanField(
                        default=False, verbose_name="Vorschlag angezeigt"
                    ),
                ),
                (
                    "outcome_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ergebnis erfasst"
                    ),
                ),
                (
                    "chosen_quarter_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Gewählt Quartier-ID"
                    ),
                ),
                (
                    "chosen_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Gewählt Monat"
                    ),
                ),
                (
                    "overridden",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Vorschlag überstimmt"
                    ),
                ),
            ],
            options={
                "verbose_name": "NL-Lern-Signal",
                "verbose_name_plural": "NL-Lern-Signale",
                "indexes": [
                    models.Index(
                        fields=["kind", "created_at"],
                        name="booking_nli_kind_4e20d6_idx",
                    ),
                    models.Index(
                        fields=["pseudonym", "created_at"],
                        name="booking_nli_pseudon_a4f16d_idx",
                    ),
                ],
            },
        ),
    ]
