# Generated by Django 5.2.15 on 2026-07-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0076_opsconfig_nl_learning_enabled_nlinteraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NlProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erzeugt"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("alias", "Alias"), ("ranking", "Reihung")],
                        max_length=8,
                        verbose_name="Klasse",
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Idempotenz-Schlüssel"
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Nutzlast")),
                ("evidence", models.JSONField(default=dict, verbose_name="Belege")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "offen"),
                            ("accepted", "übernommen"),
                            ("rejected", "abgelehnt"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entschieden am"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entschieden von",
                    ),
                ),
            ],
            options={
                "verbose_name": "NL-Lern-Vorschlag",
                "verbose_name_plural": "NL-Lern-Vorschläge",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "kind"], name="booking_nlp_status_cf8914_idx"
                    )
                ],
            },
        ),
    ]
