# Generated by Django 5.2.15 on 2026-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0076_opsconfig_nl_learning_enabled_nlinteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="lottery_max_parallel_units",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Wie viele *gleichzeitig* (überlappend) belegte Unterkünfte ein einzelnes Mitglied aus EINER Losung höchstens gewinnen darf. Standard 1 („man kann nicht an zwei Orten zugleich sein“): so werden mehrere Wünsche fürs selbe Fenster zu reinen Ausweich-Alternativen – nur einer gewinnt, die Chance steigt nicht und niemand kann mehrere gleichwertige Einheiten monopolisieren. 0 = unbegrenzt. Gilt PRO Mitglied/Login (ein Tandem-Paar = zwei Konten kann also je eine Einheit gewinnen). Ergänzt die per-Anteil wirkende Saison-Regel „max. Wohneinheiten gleichzeitig“ (ADR 0114).",
                verbose_name="Losung: max. gleichzeitige Einheiten je Mitglied",
            ),
        ),
    ]
