# Generated by Django 5.2.15 on 2026-07-24 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0077_nlproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NlLexiconEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Übernommen am"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("alias", "Alias"), ("ranking", "Reihung")],
                        max_length=8,
                        verbose_name="Klasse",
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Schlüssel"
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Nutzlast")),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "evidence",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Beleg-Snapshot"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Übernommen von",
                    ),
                ),
                (
                    "source_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_entries",
                        to="booking.nlproposal",
                        verbose_name="Aus Vorschlag",
                    ),
                ),
            ],
            options={
                "verbose_name": "NL-Lexikon-Eintrag",
                "verbose_name_plural": "NL-Lexikon-Einträge",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["active", "kind"], name="booking_nll_active_996b5b_idx"
                    )
                ],
            },
        ),
    ]
