# Generated by Django 5.1.15 on 2026-06-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0013_member_city_member_iban_member_legal_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kurzbeschreibung"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preis (brutto)"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("stueck", "Stück"),
                            ("kg", "kg"),
                            ("liter", "Liter"),
                            ("bund", "Bund"),
                            ("glas", "Glas"),
                            ("portion", "Portion"),
                        ],
                        default="stueck",
                        max_length=10,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "vat_rate",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "0 %"), (7, "7 %"), (19, "19 %")],
                        default=7,
                        verbose_name="MwSt",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ware", "Ware"),
                            ("dienstleistung", "Dienstleistung"),
                        ],
                        default="ware",
                        max_length=14,
                        verbose_name="Art",
                    ),
                ),
                (
                    "needs_date",
                    models.BooleanField(
                        default=False,
                        help_text="z.B. Sauna: Mitglied gibt beim Kauf ein Datum an.",
                        verbose_name="Termin nötig",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="Sortierung"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Produkt / Dienstleistung",
                "verbose_name_plural": "Produkte & Dienstleistungen",
                "ordering": ["group__sort_order", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Name"),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Symbol (Emoji)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="Sortierung"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Produktgruppe",
                "verbose_name_plural": "Produktgruppen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShopConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coop_name",
                    models.CharField(
                        default="Re:Hof eG",
                        max_length=160,
                        verbose_name="Genossenschaft",
                    ),
                ),
                (
                    "coop_address",
                    models.TextField(blank=True, verbose_name="Anschrift"),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Steuernummer/USt-IdNr."
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=34, verbose_name="IBAN (Zahlungsempfang)"
                    ),
                ),
                (
                    "bic",
                    models.CharField(blank=True, max_length=11, verbose_name="BIC"),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="HL", max_length=8, verbose_name="Rechnungs-Präfix"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hofladen-Einstellungen",
                "verbose_name_plural": "Hofladen-Einstellungen",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Rechnungsnummer"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Jahr")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Monat")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("paid", "Als bezahlt gemeldet"),
                            ("confirmed", "Bestätigt (archiviert)"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "paid_reported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bezahlt gemeldet am"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bestätigt am"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Empfänger"
                    ),
                ),
                (
                    "recipient_address",
                    models.TextField(blank=True, verbose_name="Empfänger-Anschrift"),
                ),
                (
                    "coop_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Genossenschaft"
                    ),
                ),
                (
                    "coop_address",
                    models.TextField(blank=True, verbose_name="Anschrift"),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Steuernummer"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(blank=True, max_length=11, verbose_name="BIC"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "ordering": ["-year", "-month", "number"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Bezeichnung")),
                ("unit", models.CharField(max_length=10, verbose_name="Einheit")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Einzelpreis (brutto)",
                    ),
                ),
                ("vat_rate", models.PositiveSmallIntegerField(verbose_name="MwSt")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="Menge"
                    ),
                ),
                (
                    "service_date",
                    models.DateField(blank=True, null=True, verbose_name="Termin"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erfasst"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="shop.invoice",
                        verbose_name="Rechnung",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_items",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="line_items",
                        to="shop.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkaufsposition",
                "verbose_name_plural": "Einkaufspositionen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="shop.productgroup",
                verbose_name="Gruppe",
            ),
        ),
    ]
