# Generated by Django 5.1.15 on 2026-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="book_with_stay",
            field=models.BooleanField(
                default=False,
                help_text="z.B. Endreinigung: erscheint im Bestätigungsschritt der Buchung und kann gleich mitgebucht werden.",
                verbose_name="Beim Buchen einer Unterkunft anbieten",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unavailable_weekdays",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Komma-getrennt 0=Mo … 6=So. An diesen Wochentagen (Abreisetag) ist die Dienstleistung nicht buchbar – z.B. Endreinigung am Wochenende.",
                max_length=20,
                verbose_name="Nicht möglich an Wochentagen",
            ),
        ),
    ]
