# Generated by Django 5.1.15 on 2026-06-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_allocation_companions"),
        ("shop", "0002_product_book_with_stay_product_unavailable_weekdays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eingekauft am"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkauf",
                "verbose_name_plural": "Einkäufe (bestätigt)",
                "ordering": ["-confirmed_at"],
            },
        ),
        migrations.AddField(
            model_name="lineitem",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.purchase",
                verbose_name="Einkauf",
            ),
        ),
    ]
