# Generated by Django 5.1.15 on 2026-06-22 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_opsconfig"),
        ("shop", "0004_backfill_purchases"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Fällig am"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zuletzt erinnert am"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Gesetzt, wenn die Dienstleistung beim Buchen mitgebucht wurde (z.B. Endreinigung) – verknüpft sie mit Quartier und Abreisetag.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_items",
                to="booking.allocation",
                verbose_name="Zugehörige Buchung",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="counts_as_cleaning",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiv, gilt diese Dienstleistung als Endreinigung und erscheint in der Reinigungsliste fürs Team (Markierung an der betroffenen Buchung).",
                verbose_name="Zählt als Endreinigung",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="payment_term_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Nach so vielen Tagen ohne Zahlungseingang gilt eine Rechnung als überfällig (für die Zahlungserinnerung).",
                verbose_name="Zahlungsziel (Tage)",
            ),
        ),
    ]
