# Generated by Django 5.1.15 on 2026-06-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_default_counts_as_cleaning"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Importiert am"
                    ),
                ),
                (
                    "filename",
                    models.CharField(blank=True, max_length=200, verbose_name="Datei"),
                ),
                (
                    "fmt",
                    models.CharField(
                        default="csv", max_length=16, verbose_name="Format"
                    ),
                ),
                (
                    "n_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Zeilen gesamt"
                    ),
                ),
                (
                    "n_imported",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Neu übernommen"
                    ),
                ),
                (
                    "n_matched",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Automatisch zugeordnet"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontoauszug-Import",
                "verbose_name_plural": "Kontoauszug-Importe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booked_on",
                    models.DateField(blank=True, null=True, verbose_name="Buchungstag"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Betrag"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, verbose_name="Verwendungszweck"),
                ),
                (
                    "counterparty_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Zahlungsbeteiligte:r"
                    ),
                ),
                (
                    "counterparty_iban",
                    models.CharField(blank=True, max_length=40, verbose_name="IBAN"),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Fingerabdruck"
                    ),
                ),
                ("raw", models.TextField(blank=True, verbose_name="Rohzeile")),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Übernommen am"
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zugeordnet am"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hinweis"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="shop.bankimport",
                        verbose_name="Import",
                    ),
                ),
                (
                    "matched_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transactions",
                        to="shop.invoice",
                        verbose_name="Zugeordnete Rechnung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zahlungseingang",
                "verbose_name_plural": "Zahlungseingänge (Kontoauszug)",
                "ordering": ["-booked_on", "-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["matched_invoice"],
                        name="shop_banktr_matched_65561d_idx",
                    )
                ],
            },
        ),
    ]
