# Generated by Django 5.1.15 on 2026-06-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_externalconfig_guest_quarter_external_bookable_and_more"),
        ("shop", "0007_bankimport_banktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="booking.guest",
                verbose_name="Externer Gast",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_items",
                to="booking.guest",
                verbose_name="Externer Gast",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="booking.member",
                verbose_name="Mitglied",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_items",
                to="booking.member",
                verbose_name="Mitglied",
            ),
        ),
    ]
