# Generated by Django 5.1.15 on 2026-06-24 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_invoice_guest_lineitem_guest_alter_invoice_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid_online_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Online bezahlt am"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Leer = Überweisung; sonst Online-Zahldienst (z. B. „mollie“).",
                max_length=20,
                verbose_name="Bezahlt über",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="mollie_api_key",
            field=models.CharField(
                blank=True,
                help_text="LEER = eingebauter TEST-Modus (simuliert, ohne Konto/Gebühren). Ein „test_…“-Key nutzt Mollies Testumgebung (ebenfalls kostenlos), ein „live_…“-Key die echte Bezahlung.",
                max_length=64,
                verbose_name="Mollie API-Key",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="payments_active",
            field=models.BooleanField(
                default=True,
                help_text="Schaltet die Online-Bezahlung (Mollie) für Hofladen-Rechnungen UND externe Gäste frei.",
                verbose_name="Online-Bezahlung aktiv",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="mollie", max_length=20, verbose_name="Anbieter"
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Anbieter-Zahlungs-ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Betrag"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Währung"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("paid", "Bezahlt"),
                            ("failed", "Fehlgeschlagen"),
                            ("expired", "Abgelaufen"),
                            ("canceled", "Abgebrochen"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Verwendungszweck"
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Bezahlseite"
                    ),
                ),
                (
                    "is_sandbox",
                    models.BooleanField(default=False, verbose_name="Test-Modus"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bezahlt am"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shop.invoice",
                        verbose_name="Rechnung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Online-Zahlung",
                "verbose_name_plural": "Online-Zahlungen",
                "ordering": ["-created_at"],
            },
        ),
    ]
