# Generated by Django 5.1.15 on 2026-06-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_invoice_paid_online_at_invoice_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfig",
            name="board",
            field=models.CharField(
                blank=True,
                help_text="z. B. Namen des Vorstands (für Rechnung/Impressum).",
                max_length=200,
                verbose_name="Vorstand",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Erscheint auf Rechnungen und im Hilfebereich für externe Gäste.",
                max_length=254,
                verbose_name="Kontakt-E-Mail",
            ),
        ),
    ]
