# Generated by Django 5.1.15 on 2026-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0028_beds24import_alter_allocation_source_beds24importrow"),
        ("shop", "0010_shopconfig_board_shopconfig_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfig",
            name="payments_test_mode",
            field=models.BooleanField(
                default=True,
                help_text="AN = eingebaute Test-Bezahlseite, es fließt kein echtes Geld. Für den Echtbetrieb ausschalten UND einen Mollie-Key hinterlegen. Solange dieser Haken AN ist, werden Rechnungen NUR simuliert beglichen.",
                verbose_name="Test-Modus (simuliert, ohne Konto/Gebühren)",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="mollie_api_key",
            field=models.CharField(
                blank=True,
                help_text="Für den Echtbetrieb (Test-Modus AUS). Ein „test_…“-Key nutzt Mollies kostenlose Testumgebung, ein „live_…“-Key die echte Bezahlung.",
                max_length=64,
                verbose_name="Mollie API-Key",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="shop_invoic_status_0b915b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["payment_method"], name="shop_invoic_payment_f05edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="shop_invoic_status_ce20b1_idx"
            ),
        ),
    ]
