# Generated by Django 5.1.15 on 2026-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_shopconfig_payments_test_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="small_business",
            field=models.BooleanField(
                default=False, verbose_name="Kleinunternehmer (§19)"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_note",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Steuer-Hinweis"
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="imprint_extra",
            field=models.TextField(
                blank=True,
                help_text="Wird unter den Pflichtangaben ausgegeben (z. B. Aufsichtsbehörde, Hinweis zur Streitschlichtung).",
                verbose_name="Impressum – Zusatztext (optional)",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="privacy_policy",
            field=models.TextField(
                blank=True,
                help_text="Pflichttext nach DSGVO (Art. 13). Leer = Seite zeigt nur einen Platzhalter samt Kontakt.",
                verbose_name="Datenschutzerklärung",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="register_court",
            field=models.CharField(
                blank=True,
                help_text="Fürs Impressum, z. B. „Amtsgericht Frankfurt (Oder)“.",
                max_length=120,
                verbose_name="Registergericht",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="register_number",
            field=models.CharField(
                blank=True,
                help_text="Fürs Impressum, z. B. „GnR 123“.",
                max_length=40,
                verbose_name="Genossenschaftsregister-Nr.",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="small_business",
            field=models.BooleanField(
                default=False,
                help_text="AN: Rechnungen OHNE Umsatzsteuer-Ausweis, mit §19-Hinweis – wähle das, wenn die Genossenschaft unter den Umsatzgrenzen liegt (Vorjahr ≤ 25.000 € und laufendes Jahr ≤ 100.000 €). AUS (Regelbesteuerung): MwSt wird je Satz ausgewiesen (Lebensmittel/Übernachtung 7 %, Dienstleistungen 19 %). Achtung: Bei AN darf KEINE MwSt auf der Rechnung stehen (sonst §14c UStG), bei AUS MUSS sie ausgewiesen werden. Status bitte mit dem Steuerberater klären.",
                verbose_name="Kleinunternehmer (§19 UStG)",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="small_business_note",
            field=models.CharField(
                default="Gemäß § 19 UStG wird keine Umsatzsteuer berechnet (Kleinunternehmer).",
                help_text="Wird bei aktivem Kleinunternehmer-Modus auf der Rechnung gedruckt.",
                max_length=200,
                verbose_name="§19-Hinweis auf der Rechnung",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="terms_agb",
            field=models.TextField(
                blank=True,
                help_text="Allgemeine Geschäftsbedingungen für die Website/Buchungen. Leer = AGB-Seite wird nicht verlinkt.",
                verbose_name="AGB (Anzeigetext)",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="vat_id",
            field=models.CharField(
                blank=True,
                help_text="Umsatzsteuer-Identifikationsnummer nach §27a UStG, z. B. DE123456789.",
                max_length=20,
                verbose_name="USt-IdNr. (falls vorhanden)",
            ),
        ),
    ]
