# Generated by Django 5.1.15 on 2026-06-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_invoice_small_business_invoice_tax_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopconfig",
            options={
                "verbose_name": "Rechtliche & Zahlungs-Einstellungen",
                "verbose_name_plural": "Rechtliche & Zahlungs-Einstellungen",
            },
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="privacy_policy",
            field=models.TextField(
                blank=True,
                help_text="Pflichttext nach DSGVO (Art. 13). Eine anpassbare Vorlage samt Checkliste steht in docs/DATENSCHUTZ-VORLAGE.md – Platzhalter [in eckigen Klammern] ersetzen. Leer = Seite zeigt nur einen Platzhalter samt Kontakt.",
                verbose_name="Datenschutzerklärung",
            ),
        ),
    ]
