# Generated by Django 5.1.15 on 2026-06-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_shopconfig_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalInvoice",
            fields=[],
            options={
                "verbose_name": "Rechnung (externe Buchung)",
                "verbose_name_plural": "Rechnungen (externe Buchungen)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shop.invoice",),
        ),
    ]
