# Generated by Django 5.1.15 on 2026-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_externalinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="terminal_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="Terminal-Referenz",
            ),
        ),
    ]
