# Generated by Django 5.1.15 on 2026-06-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0038_pendinguser"),
        ("shop", "0015_purchase_terminal_ref"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lineitem",
            index=models.Index(
                fields=["member", "purchase", "invoice"],
                name="shop_lineit_member__7f9e4e_idx",
            ),
        ),
    ]
