# Generated by Django 5.2.15 on 2026-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_lineitem_shop_lineit_member__7f9e4e_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfig",
            name="allow_self_report_paid",
            field=models.BooleanField(
                default=True,
                help_text="AN (Standard): Mitglieder/Gäste können auf der Rechnung melden, dass sie überwiesen haben (bestätigt wird der Eingang weiterhin per Kontoabgleich). AUS: der Knopf entfällt – dann zählt allein der Kontoabgleich bzw. die Online-Zahlung (ADR 0078).",
                verbose_name="Selbst-Meldung „Habe ich überwiesen“ erlauben",
            ),
        ),
    ]
