# Generated by Django 5.2.15 on 2026-07-02 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0048_bookingperiod_wish_reminder1_at_and_more"),
        ("shop", "0017_shopconfig_allow_self_report_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="needs_approval",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiv, wird die Leistung beim Buchen nur ANGEFRAGT (nicht sofort abgerechnet) – die Betriebsleitung bestätigt oder lehnt sie im Verwaltungs-Dashboard ab, erst dann entsteht die Rechnungs-Position. Für Leistungen mit Abstimmung, z.B. die Endreinigung (ADR 0081).",
                verbose_name="Muss von der Betriebsleitung bestätigt werden",
            ),
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="Termin (Abreisetag)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Angefragt"),
                            ("confirmed", "Bestätigt"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="requested",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Anmerkung/Grund"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Angefragt am"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entschieden am"
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="booking.allocation",
                        verbose_name="Zugehörige Buchung",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entschieden von",
                    ),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="shop.lineitem",
                        verbose_name="Rechnungs-Position (nach Bestätigung)",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="booking.member",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="shop.product",
                        verbose_name="Dienstleistung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienstleistungs-Anfrage",
                "verbose_name_plural": "Dienstleistungs-Anfragen",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "service_date"],
                        name="shop_servic_status_dfe6ab_idx",
                    )
                ],
            },
        ),
    ]
