# Generated by Django 5.2.15 on 2026-07-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_product_needs_approval_servicerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reminder_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Wie oft wurde bereits erinnert/gemahnt (1./2./… Mahnung).",
                verbose_name="Erinnerungen/Mahnstufe",
            ),
        ),
        migrations.AddField(
            model_name="shopconfig",
            name="reminder_interval_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Frühestens nach so vielen Tagen darf dieselbe Rechnung erneut erinnert/gemahnt werden (verhindert sofortiges Doppel-Mahnen). Jede Erinnerung zählt eine Stufe hoch (1./2./… Mahnung).",
                verbose_name="Mindestabstand Erinnerungen (Tage)",
            ),
        ),
    ]
