# Generated by Django 5.2.15 on 2026-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_invoice_reminder_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("paid", "Als bezahlt gemeldet"),
                    ("confirmed", "Bestätigt (archiviert)"),
                    ("cancelled", "Storniert"),
                ],
                default="open",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
